import React from "react";
import Link from "next/link";
import { client } from "../../lib/client";
import PerfectBanner from "../components/PerfectBanner";
import Newsletter from "../components/Newsletter";
import { NextSeo } from "next-seo";

const Home = () => (
<>
  {/*<NextSeo
    title="Macaron Magic"
    description="Great tasting home made macarons"
  />*/}

  <div>
    <div className="frontlogo">
      <div className="banner">
        <span className="tagline">Luxury macarons made by hand</span>
        <span>
          <Link className="shop-now" href="/shop">
            Shop Now
          </Link>
        </span>
      </div>
    </div>

    <div className="intro">
      <p>
        Welcome to Macaron Magic - the home of great-tasting,
        luxurious macarons, made by hand here in our workshop in the
        Peak District.
      </p>

      <p>
        We have carefully chosen a select range of flavors for your
        delight, ready for you to enjoy - just imagine...biting into
        each one, where it
        practically melts in your mouth...yum!
      </p>
      <p>
        To start, browse over to our shop where you will see the full
        range available - we&apos;ll be adding more over time. If you have
        any questions, please do let us know - our contact details are
        at the bottom of this page.
      </p>
    </div>

    <PerfectBanner />
    <Newsletter />
  </div>
</>
);  

/* ADD SERVERSIDE PROPS HERE */

export default Home;





/* 
import Head from "next/head";
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        <main className={styles.main}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js logo"
            width={180}
            height={38}
            priority
          />
          <ol>
            <li>
              Get started by editing <code>src/pages/index.js</code>.
            </li>
            <li>Save and see your changes instantly.</li>
          </ol>

          <div className={styles.ctas}>
            <a
              className={styles.primary}
              href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              <Image
                className={styles.logo}
                src="/vercel.svg"
                alt="Vercel logomark"
                width={20}
                height={20}
              />
              Deploy now
            </a>
            <a
              href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
              className={styles.secondary}
            >
              Read our docs
            </a>
          </div>
        </main>
        <footer className={styles.footer}>
          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            <Image
              aria-hidden
              src="/file.svg"
              alt="File icon"
              width={16}
              height={16}
            />
            Learn
          </a>
          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            <Image
              aria-hidden
              src="/window.svg"
              alt="Window icon"
              width={16}
              height={16}
            />
            Examples
          </a>
          <a
            href="https://nextjs.org?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            <Image
              aria-hidden
              src="/globe.svg"
              alt="Globe icon"
              width={16}
              height={16}
            />
            Go to nextjs.org →
          </a>
        </footer>
      </div>
    </>
  );
}
*/